name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Autenticando no Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker build chatservice
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            fabricioveronez/conversao-temperatura:v${{ github.run_number }}
            fabricioveronez/conversao-temperatura:latest
      - name: Docker build webapp
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: |
            fabricioveronez/conversao-temperatura:v${{ github.run_number }}
            fabricioveronez/conversao-temperatura:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          resource-group: live
          cluster-name: live

      # - name: Deploy das aplicações
      #   uses: Azure/k8s-deploy@v4.9
      #   with:
      #     manifests: |
      #       k8s/deploy-chatservice.yaml
      #       k8s/deploy-webapp.yaml
      #     images: |
      #       fabricioveronez/conversao-temperatura:v${{ github.run_number }}
      #       fabricioveronez/conversao-temperatura:v${{ github.run_number }}
