name: CI-CD
on: 
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Autenticando no Docker Registry
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USR }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Docker build chatservice
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            fabricioveronez/conversao-temperatura:v${{ github.run_number }}
            fabricioveronez/conversao-temperatura:latest
      - name: Docker build webapp
        uses: docker/build-push-action@v4.1.1
        with: 
          context: ./webapp
          file: ./webapp/Dockerfile
          push: true
          tags: |
            fabricioveronez/conversao-temperatura:v${{ github.run_number }}
            fabricioveronez/conversao-temperatura:latest
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3

      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          # Resource Group Name
          resource-group: 
          # AKS Cluster Name
          cluster-name: 
          # AKS Cluster Subscription
          subscription: # optional
          # Get cluster admin credentials. Values: true or false
          admin: # optional
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: # optional

      - name: Deploy das aplicações
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: |
            k8s/deploy-chatservice.yaml
            k8s/deploy-webapp.yaml
          images: |
            fabricioveronez/conversao-temperatura:v${{ github.run_number }}
            fabricioveronez/conversao-temperatura:v${{ github.run_number }}
