# This is a basic workflow to help you get started with Actions

name: CI

# Controls when te workflow will run **(EVENTOS)
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  CI:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup do NodeJS
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 16.13.2

      - name: Instalação do Mocha e dos pacotes para teste
        run: |
          cd src;
          npm install -g mocha;
          npm install;

      - name: Execução do teste
        run: mocha src/test/convert.js

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CEZANILTOMSILVA }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Construção da imagem Docker
        # You may pin to the exact commit or the version.
        # uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4
        uses: docker/build-push-action@v6.15.0
        with:
          context: src
          file: ./src/Dockerfile
          push: true
          tags: |
            cezaniltomsilva/aula-conversao-temperatura:{{ github.run_number }}
            cezaniltomsilva/aula-conversao-temperatura:latest
            
